apply from: 'gradle/versions.gradle'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation('org.junit.jupiter:junit-jupiter',
            "org.testng:testng:7.4.0",
            "org.junit.jupiter:junit-jupiter-params:5.10.0")
    implementation(
            'com.codeborne:selenide:7.4.2',
            'com.github.javafaker:javafaker:1.0.2',
            'com.microsoft.playwright:playwright:1.47.0',
            'com.fasterxml.jackson.core:jackson-databind:2.18.1',
            'io.rest-assured:rest-assured:5.5.0',
            'org.assertj:assertj-core:3.26.3',
            "io.qameta.allure:allure-selenide:$allureVersion",
            "io.qameta.allure:allure-rest-assured:$allureVersion",
            "io.qameta.allure:allure-junit5:$allureVersion"
    )

    testRuntimeOnly 'org.slf4j:slf4j-simple:2.0.6'
}